# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4508a602d2e02742eb5e2d0a531ee661a79e5a959d98cf10100146d5e989317ee64dcd3ac254537d2052420b8aa3fa06eb89f819b6a49fd446dbc849f403965

test:
  secret_key_base: a63519b390638d25d46b6ef5df7c8aa2eeb19a054ea70d9a99dddb5152133826c76755e0483d01e40adfc27a3be946f88949df02f6a3fcf709cca4312eaf4e03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
